export const mockData = [
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
  {
    id: "",
    author: "",
    width: "",
    height: "",
    url: "",
    download_url: "",
    isLoaded: true,
  },
]
