name: lint&build&tests
on: [push]
env:
  REACT_APP_MOCKAROO_API_KEY: ${{ secrets.REACT_APP_MOCKAROO_API_KEY }}
jobs:
  build:
    name: build-site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn github || echo "Test failed"; exit 1
